### ISSUE TITLE
建议增加热更新功能

### ISSUE THREAD

**Issue by moguv587** [tcdw/oneanime.js#1]
感谢大佬，我测试了下，运行后添加文件夹或者往文件夹塞东西，他不会自动更新
大佬有空可以考虑下增加这个

**Comment by tcdw** [comment]
我不认为这个功能是有必要的，因为这个工具的期望用法是，你把你需要的图片丢进去，就让它一直运行了。
同时，增加热更新功能，我这边的代码量要进一步增加，导致程序维护难度上升。
如果你真的需要，可以考虑一下 [pm2 的 watch 功能](https://pm2.keymetrics.io/docs/usage/watch-and-restart/)。
